[theme]
primaryColor = "#A8D8EA"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#FFE5E5"
textColor = "#4A5568"
font = "sans serif"

[server]
headless = true
port = 8503
enableCORS = true
enableXsrfProtection = false

[browser]
gatherUsageStats = false
